apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: echo-server-falkenstein
  namespace: tests
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`falkenstein.ciliumdemo.entengott.com`)
      kind: Rule
      services:
        - name: echo-server
          port: 8080
  tls:
    certResolver: letsencrypt
